{{- if .Values.deployment.awsSecrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "pg-deploy.name" . }}
spec:
  provider: aws
  secretObjects:
  - secretName: {{ include "pg-deploy.name" . }}
    type: Opaque
    data:
      {{- range .Values.deployment.awsSecrets }}
      - objectName: "{{ .objectName }}"
        key: "{{ .key }}"
      {{- end }}
  parameters:
    objects: |
      - objectName: {{ if hasPrefix "sandbox" .Values.env }}integration/{{ .Values.name }}{{ else }}{{ .Values.env }}/{{ .Values.name }}{{ end }}
        objectType: secretsmanager
        jmesPath:
          {{- range .Values.deployment.awsSecrets }}
          - path: {{ .key }}
            objectAlias: {{ .objectName }}
          {{- end }}
{{- end }}
