apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ if hasPrefix "sandbox" .Values.env }}arn:aws:iam::199699173728:role/integration-secretmanager-role{{ else }}arn:aws:iam::199699173728:role/{{ .Values.env }}-secretmanager-role{{ end }}
  name: {{ include "pg-deploy.name" . }}
