apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: {{ include "pg-deploy.name" . }}
  name: {{ include "pg-deploy.name" . }}
spec:
  ports:
  - name: http-{{ .Values.service.port }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.applicationPort }}
  selector:
    app: {{ include "pg-deploy.name" . }}
  type: {{ .Values.service.type }}